import { ProfileConstant } from './ActiveProfileConstants.js'
import { getActivProfile } from '../Profiles/Profiles.js'
const baseURL = getActivProfile(ProfileConstant.Dev);

export const Url = {
  login: baseURL + 'customerFeedbackMaster',
  getProfilePic : baseURL + 'profilePic/{id}',
  getCreatedLink: baseURL + 'customerFeedbackMaster',
  questionList: baseURL + 'question/{formType}',
  getAllCustomer: baseURL + 'question/getAllCustomer',
  getProjectList: baseURL + 'question/project/{customerId}',
  authLogin: baseURL + "auth/login",
  tokenParse: baseURL + "tokenparse",
  submitFeedBack: baseURL + 'customerFeedback',
  getcustomerDetails: baseURL + 'customerFeedbackMaster/{id}',
  getcustomerFeedbackList: baseURL + 'customerFeedback/{id}',
  updateCustomerFeedback: baseURL + 'customerFeedbackMaster/{id}',
  vendorAddData: baseURL + 'kycvendorform',
  getVendorFormData: baseURL + 'kycvendorform/{id}',
  createVendorLink: baseURL + 'kycvendorregistration',
  updateVendorCreateLink: baseURL + 'vendorupdate',
  getAllCreateLink: baseURL + 'getAllKYCForm',
  generatePdf : baseURL + 'generatePdf/{id}',
  customerSatisfactionCreateLink : baseURL + 'customerSatisfactionMaster',
  getCustomerSatisfactionCreateLink : baseURL + 'customerSatisfactionMaster',
  customerSatisfactionSubmitFeedback : baseURL + 'customerSatisfactionSurvey',
  getQuestionList : baseURL + 'question/{formType}',
  getCreateLinkLoginData : baseURL + 'customerSatisfactionMaster/{custSatisfactionId}',
  getSubmitData : baseURL + 'customerSatisfactionSurvey/{id}',
  getCustomerEmailMobile : baseURL + 'customer/{id}',
  getEmployeeDetails :baseURL + 'employee',
  getEmployeeSatffid :baseURL + 'employee/{staffId}',
  submitEmployeePerformes :baseURL + 'employeePerformenceMaster',
  getEmployeePerformes :baseURL + 'employeePerformenceMaster',
  updateEmployeeDetails :baseURL + 'employeePerformenceMaster/{id}',
  getEmployeeDetailsById : baseURL + 'employeePerformenceMaster/{id}',
  submitEmployeeAnswer : baseURL + 'employeeFeedback',
  getSubmittedEmployeeFeedback : baseURL + 'employeeFeedback/{id}',
  sentmailCustomerserve : baseURL + 'send/{id}',
  updateCustomersatisfactionSurvey : baseURL + 'customerSatisfactionMaster/{id}',
  getEmployeeProjectList : baseURL + 'projectlist/{staffid}',
  getProjectManagerDetails : baseURL + 'projectManager',
  getProjectManagerEmail : baseURL + 'employeeDetails/{staffid}',
  sendProjectFeedbackEmail : baseURL + 'sendMailToProjectEnd/{id}',
  sendProjectManagerEmail : baseURL + 'sendMailToManager/{id}',
  sendVendorEmail : baseURL + 'sendMailToVendor/{id}',
  getEmployeeEmail : baseURL + 'employeeDetails/{staffId}',
  getEmail : baseURL + 'addressMaster/{id}',
  getStateFromGstNo : baseURL + 'getstate/{code}',
  getAllCountry : baseURL + 'getAllCountry',
  uploadForm : baseURL + 'upload',
  saveCustomerFeedbackMailData : baseURL + 'saveCustomerFeedbackMail',
  savecustomerSatisfactionMaildata : baseURL + 'saveCustomerSatisfactionMail',
  saveEmployeeMailData: baseURL + 'saveEmployeePerformanceMail',
  saveVendorMailData: baseURL + 'saveVendorOnboardingEmail',
  getRntLogo : baseURL + 'getrntlogo/rntlogo.svg'
};
